### ISSUE TITLE
Random number generator used by default is Not Secure

### ISSUE THREAD

**Issue by sirk390** [starkbank/ecdsa-python#1]
It seems  the random number generator used by default when generating a private key is not secure:
When you call: 
    >privateKey = PrivateKey()
It does 
      randint(1, curve.N - 1)
 While "randint" is imported from "random" module.
 Instead random should use " random.SystemRandom"

**Comment by rcmstark** [comment]
What you think now: 

https://github.com/starkbank/ecdsa-python/pull/2/files

**Comment by sirk390** [comment]
Yes, this is good, but you have also the same issue for signature (ecdsa.py line 14).

**Comment by rcmstark** [comment]
True. I updated the PR, I will close this issue now.
