### ISSUE TITLE
Python <-> Java interface

### ISSUE THREAD

**Issue by svaidyans** [starkbank/ecdsa-python#16]
Hi,

Thanks for this wonderful lib.  

I am trying to use this to sign and verify in Java, using your "Ecdsa-java" but have trouble sending the signature from Python to Java.  If you could kindly provide an example to illustrate signing in Python and verifying in Java that would be really great.

Many thanks,
Vaidya.

**Comment by cdottori-stark** [comment]
Hi Vaidya,

Glad you liked the lib!

Here is the python example:

`
from ellipticcurve.ecdsa import Ecdsa
from ellipticcurve.privateKey import PrivateKey

privateKey = PrivateKey()  # generating random private key
publicKey = privateKey.publicKey()
print("publicKey: {}".format(publicKey.toPem()))

message = "My signed message"
print("message: {}".format(message))

signature = Ecdsa.sign(message, privateKey)

print("\nsignature: {}".format(signature.toBase64()))
`

which printed something like:

`
publicKey: -----BEGIN PUBLIC KEY-----
MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEqte8sXct94Dd/z+x3maCYxpCPDhL8L3G
rMoiBnKl+P5Nurku5N0X5EmW4PkULALGbC0cKLB+pvTAdRk9JOJagQ==
-----END PUBLIC KEY-----

message: My signed message

signature: MEUCIQD0CjtxAdWo7w59n4aThZRWIqW99DQ4KOF9YFhbxzXywQIgLSaR5inT+qTy5h05OnXruCnSqAWOzT7i6EkaE90xZ4g=
`

And here is the corresponding java example:

`
PublicKey publicKey = PublicKey.fromPem("-----BEGIN PUBLIC KEY-----\n" +
        "MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEqte8sXct94Dd/z+x3maCYxpCPDhL8L3G\n" +
        "rMoiBnKl+P5Nurku5N0X5EmW4PkULALGbC0cKLB+pvTAdRk9JOJagQ==\n" +
        "-----END PUBLIC KEY-----");

String message = "My signed message";

String base64 = "MEUCIQD0CjtxAdWo7w59n4aThZRWIqW99DQ4KOF9YFhbxzXywQIgLSaR5inT+qTy5h05OnXruCnSqAWOzT7i6EkaE90xZ4g=";
Signature signature = Signature.fromBase64(new ByteString(base64.getBytes()));

System.out.println(Ecdsa.verify(message, signature, publicKey));
`

which prints "true".

And that's it!

Sorry about the delay, and hope you find it useful!

**Comment by svaidyans** [comment]
Fantastic, thank you!
