### ISSUE TITLE
ecdsa point addition

### ISSUE THREAD

**Issue by su314ka** [starkbank/ecdsa-python#19]
Hello,

Can I use ecdsa point addition or multiplication using this library?
Thanks!

**Comment by cdottori-stark** [comment]
Hello,

It is not the exposed functionality of the library and, as such, it can more easily suffer breaking changes. However, it is indeed possible to perform ecdsa point addition and multiplication using the internal Math.multiply and Math.add methods.

Hope you find it useful!
