### ISSUE TITLE
verify() unstable results for certain custom defined curves

### ISSUE THREAD

**Issue by cyphre** [starkbank/ecdsa-python#24]
I noticed when defining custom elliptic curve in some cases the verify() doesn't always return TRUE even for valid signatures.

To fix that I had to change these lines in verify() method like this:

`add = Math.add(u1, u2, P=curve.P, A=curve.A)`
`return sigR == add.x`

to:

`add = Math.add(u1, u2, P=curve.P, A=curve.A)`
`modX = add.x % curve.N`
`return sigR == modX`

After this fix the verify() results were stable on every valid signature.

**Comment by rcmstark** [comment]
@cyphre Thank you for the contribution. If you could send a Pull Request it will be accepted.

**Comment by cdottori-stark** [comment]
Fix deployed on version 1.1.1
