### ISSUE TITLE
check that the public keys lie on the curve.?

### ISSUE THREAD

**Issue by Noname400** [starkbank/ecdsa-python#31]
hello, tell me how to check that the public keys lie on the curve.?
and how to check that after the operation of multiplication I left the border of the curve?

**Comment by massaru-stark** [comment]
Hello,

The public key is already completely verified once you import it using this library (using PublicKey.fromPem()). You can take a look at how this is implemented [right here](https://github.com/starkbank/ecdsa-python/blob/7e4d78a8d1d90bed2ae974f7ba90f98d29f87cac/ellipticcurve/publicKey.py#L69).

Best,
